### PR TITLE
added a passwordgenerator program.

### PR DESCRIPTION
**Pull request by sajdakabir**
added a passwordgenerator program write in python add in python folder.

### CODE REVIEW

**Comment by Gupta-Nikhil85** [comment]
I had just added the miscellaneous folder in python.
Please do make a pull request by adding the file in that folder.
Sorry for the inconvinience.

**Comment by sajdakabir** [comment]
@Gupta-Nikhil85  okay

**Comment by sajdakabir** [comment]
i'm update the file structure

**Comment by Gupta-Nikhil85** [comment]
@sajdakabir  do fetch the upstream first. 
Your forked repo is 17 comments behind this repo.

**Pull request merged**
